services:
  portfolio-reverse-proxy:
    image: traefik:v3.1
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=me@nikicaraznatovic.me"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "CF_API_EMAIL=nikicaraznatovic123@gmail.com"
      - "CF_API_KEY=2d3fbdbd06b07ba39944989bb563fee0e2677"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  portfolio_v3:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_v3-secure.rule=Host(`nikicaraznatovic.me`)"
      - "traefik.http.routers.portfolio_v3-secure.entrypoints=websecure"
      - "traefik.http.routers.portfolio_v3-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio_v3.rule=Host(`nikicaraznatovic.me`)"
      - "traefik.http.routers.portfolio_v3.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.portfolio_v3.middlewares=redirect-to-https"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
volumes:
  node_modules:
  letsencrypt:
