version: "3.7"

services:
  # TODO: Add a dev service
  # dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: portfolio
  #   environment:
  #     - WATCHPACK_POLLING=true
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env.local
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-prod
    ports:
      - "3000:3000"

volumes:
  node_modules:
